#!/bin/zsh

## Setup Desktops and Restore Layout --{{

bspc monitor LVDS1 -n Laptop
bspc monitor Laptop --reset-desktops Ⅰ Ⅱ Ⅲ Ⅳ Ⅴ Ⅵ

if [[ ${EXT_CONNECTED} = 1 ]]; then {
	bspc monitor VGA1 -n External
	bspc monitor External --reset-desktops web tex maple gfx
} fi;

#bspc monitor Laptop --reset-desktops I II III IV V VI

##############################
#      Restore Session       #
##############################

if [[ -s "$BSPWM_TREE" ]] {
  bspc restore --tree "$BSPWM_TREE"
  rm "$BSPWM_TREE"
} fi

if [[ -s "$BSPWM_HISTORY" ]] {
  bspc restore --history "$BSPWM_HISTORY"
  rm "$BSPWM_HISTORY"
} fi

if [[ -s "$BSPWM_STACK" ]] {
  bspc restore --stack "$BSPWM_STACK"
  rm "$BSPWM_STACK"
} fi

## --}}

## Global Settings --{{

# Makes the workspaces display correctly in case of external display

bspc config split_ratio							  0.52
bspc config border_width						  3
bspc config window_gap							  20
bspc config borderless_monocle					  true
bspc config gapless_monocle						  true

bspc config focused_border_color                  "#353535"
bspc config active_border_color                   "#191919"
bspc config normal_border_color                   "#191919"
bspc config presel_border_color                   "#a2a2a2"

bspc config focused_private_border_color          "#404040"
bspc config active_private_border_color           "#191919"
bspc config normal_private_border_color           "#191919"

#bspc config focused_border_color                 "#53A6A6"
#bspc config focused_private_border_color         "#43A6A6"
#bspc config normal_border_color                  "#395573"

bspc config auto_cancel                           true
bspc config auto_alternate                        false
bspc config history_aware_focus                   true
bspc config pointer_follows_monitor               true
bspc config pointer_follows_focus				  true
bspc config focus_follows_pointer				  true
bspc config focus_by_distance					  true

bspc config -m Laptop top_padding				  20
bspc config -m External top_padding				  20

#bspc config normal_frame_opacity                 0.0
#bspc config active_frame_opacity                 0.0
#bspc config focused_frame_opacity                0.05

## --}}

## Per Desktop Settings --{{

for n in 1 2 3 4 5 6; do
	bspc config -d ^$n border_width				  3
	bspc config -d ^$n window_gap				  20
	bspc config -d ^$n top_padding                0
	bspc config -d ^$n left_padding               0
	bspc config -d ^$n right_padding              0
	bspc config -d ^$n bottom_padding             0
done

bspc desktop ^6 --toggle floating=on

# External if connected
if [[ ${EXT_CONNECTED} -eq 1 ]]; then {
	for n in 7 8 9 10; do
		bspc config -d ^$n border_width				  3
		bspc config -d ^$n window_gap				  20
		bspc config -d ^$n top_padding                0
		bspc config -d ^$n left_padding               0
		bspc config -d ^$n right_padding              0
		bspc config -d ^$n bottom_padding             0
	done
} fi;

## --}}

## Rules --{{

if [[ ${EXT_CONNECTED} -eq 1 ]]; then {
	bspc rule -a Firefox					desktop=^7   follow=true
	bspc rule -a Gimp						desktop=^10  follow=true	floating=true
	bspc rule -a Inkscape					desktop=^10  follow=true	floating=true
	bspc rule -a geogebra-GeoGebra3D		desktop=^10  follow=true	floating=true	border=off
	bspc rule -a sun-awt-X11-XDialogPeer	desktop=^10  follow=true	floating=true	border=off
	bspc rule -a java-lang-Thread			desktop=^9   follow=true	floating=true	border=off
} else {
	bspc rule -a Firefox				    desktop=^2   follow=true
	bspc rule -a Gimp					    desktop=^6   follow=true	floating=true
	bspc rule -a Inkscape				    desktop=^6   follow=true	floating=true
	bspc rule -a geogebra-GeoGebra3D	    desktop=^6   follow=true	floating=true	border=off
} fi

bspc rule -a Gvim  desktop=^3   follow=true
bspc rule -a Sxiv  desktop=^5   follow=true
bspc rule -a mpv   desktop=^1   follow=true   border=off

## --}}

##############################
#     Autostart Programs     #
##############################

#exec mailcount &
exec pacupdates &

## Geogebra fix
$LOCAL/bin/java_nonparenting_wm_hack.sh

compton -b -r 5 -t -8 -l -8 -c -f

# Battery Level Checker
#lowbattery &

# Launches panel
panel &
